grpc:
  host: "0.0.0.0"
  port: 50055
redis:
  host: notifications_redis
  port: 6379

postgres:
  host: loms_pgbouncer
  port: 5432
  user: loms-user
  password: loms-pass
  database: loms-db
  sslmode: disable

kafka:
  brokers:
    - kafka1:29091
    - kafka2:29092
    - kafka3:29093
  topic: "loms"

tg:
  token: "1844252744:AAHkUqVCSCPN8alP5-R2hHu0tzHYeL9mNjQ"
  chatId: -1001980779808

metrics:
  host: "0.0.0.0"
  port: 7082
jaeger:
  host: jaeger
  port: 6831

log:
  preset: "dev"