version: "3.1"
services:
  checkout:
    image: checkout
    build: ./checkout/
    ports:
      - "8080:8080"
      - "8088:8088"
      - "50052:50052"
  loms:
    image: loms
    build: ./loms/
    ports:
      - "50053:50053"
  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
