grpc:
  host: "0.0.0.0"
  port: 50053
metrics:
  host: "0.0.0.0"
  port: 7081
jaeger:
  host: "0.0.0.0"
  port: 6831

postgres:
  host: loms_pgbouncer
  port: 5432
  user: loms-user
  password: loms-pass
  database: loms-db
  sslmode: disable

kafka:
  brokers:
    - kafka1:29091
    - kafka2:29092
    - kafka3:29093
  topic: "loms"

rateLimit:
  limit: 2
  periodRaw: 1s

log:
  preset: "prod"