grpc:
#  host: "0.0.0.0"
  host: localhost
  port: 50053

postgres:
#  host: loms_pgbouncer
  host: localhost
#  port: 5432
  port: 6433
  user: loms-user
  password: loms-pass
  database: loms-db
  sslmode: disable

log:
  preset: "dev"