grpc:
  host: "0.0.0.0"
  port: 50053

postgres:
  host: loms_pgbouncer
  port: 5432
  user: loms-user
  password: loms-pass
  database: loms-db
  sslmode: disable

rateLimit:
  limit: 2
  periodRaw: 1s

log:
  preset: "dev"