grpc:
  host: "0.0.0.0"
  port: 50053

postgres:
  host: loms_pgbouncer
  port: 5432
  user: loms-user
  password: loms-pass
  database: loms-db
  sslmode: disable

kafka:
  brokers:
    - "kafka1:9091"
    - "kafka2:9092"
    - "kafka3:9093"
  topic: "loms"

rateLimit:
  limit: 2
  periodRaw: 1s

log:
  preset: "dev"