token: "ZuWW6GdhjQYzDBEX3OopJNpl"
timeout: 15s

grpc:
  host: "0.0.0.0"
  port: 50052
http:
  host: localhost
  port: 8080
swagger:
  host: localhost
  port: 8088
postgres:
  host: localhost
  port: 6432
  user: checkout-user
  password: checkout-pass
  database: checkout-db
  sslmode: disable

services:
  loms: "localhost:50053"
  productService: "route256.pavl.uk:8082"

workers: 1

requestLimit: 2
requestLimitPeriod: 1s

log:
  preset: "dev"