token: "ZuWW6GdhjQYzDBEX3OopJNpl"
timeout: 15s

grpc:
  host: "0.0.0.0"
  port: 50052
http:
  host: "0.0.0.0"
  port: 8080
swagger:
  host: "0.0.0.0"
  port: 8088

services:
  loms: "loms:50053"
  productService: "route256.pavl.uk:8082"

log:
  preset: "dev"