global:
  scrape_interval: 2s
  scrape_timeout: 2s
  evaluation_interval: 1s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "checkout"
    static_configs:
      - targets:
          - "checkout:7080"

  - job_name: "loms"
    static_configs:
      - targets:
          - "loms:7081"

  - job_name: "notifications"
    static_configs:
      - targets:
          - "notifications:7082"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"